// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjxeTCz6muer7IosYaKbblUXmkx3_k48',
    appId: '1:638253020569:web:f2d4d9c63bed7046e3cf08',
    messagingSenderId: '638253020569',
    projectId: 'modern-auth-95cc9',
    authDomain: 'modern-auth-95cc9.firebaseapp.com',
    databaseURL: 'https://modern-auth-95cc9-default-rtdb.firebaseio.com',
    storageBucket: 'modern-auth-95cc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB0kTUJk9gr_sNa5vOeRTagTJVfsJoRys',
    appId: '1:638253020569:android:e214577947eecde7e3cf08',
    messagingSenderId: '638253020569',
    projectId: 'modern-auth-95cc9',
    databaseURL: 'https://modern-auth-95cc9-default-rtdb.firebaseio.com',
    storageBucket: 'modern-auth-95cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADFQAgrZrpQD7bY7ATdgvA6HzmfQkYIgQ',
    appId: '1:638253020569:ios:f030355af7f8bf69e3cf08',
    messagingSenderId: '638253020569',
    projectId: 'modern-auth-95cc9',
    databaseURL: 'https://modern-auth-95cc9-default-rtdb.firebaseio.com',
    storageBucket: 'modern-auth-95cc9.appspot.com',
    iosBundleId: 'com.example.modernAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADFQAgrZrpQD7bY7ATdgvA6HzmfQkYIgQ',
    appId: '1:638253020569:ios:f030355af7f8bf69e3cf08',
    messagingSenderId: '638253020569',
    projectId: 'modern-auth-95cc9',
    databaseURL: 'https://modern-auth-95cc9-default-rtdb.firebaseio.com',
    storageBucket: 'modern-auth-95cc9.appspot.com',
    iosBundleId: 'com.example.modernAuthentication',
  );
}
